### ISSUE TITLE
Include IDnowSDK as gradle/maven dependency

### ISSUE THREAD

**Issue by gtmn** [idnow/de.idnow.android#12]
Hi,

Is it possible for you to publish the SDK as well as a gradle or maven package?
Would be a nice enhancement to directly include the SDK into a project as a dependency.

All the best,
Matthias

**Comment by sebastianmarschall** [comment]
are there any plans on this?
it would be great if you could provide your SDK via maven and declare your WebRTC dependency.

**Comment by fr33z3** [comment]
Yes, please. That would simplify everyone's life.

**Comment by aare-undo-idnow** [comment]
Possible now when adding Github maven url. Will be properly implemented with our unified SDK
