### ISSUE TITLE
v3.4.0 Done button is not working

### ISSUE THREAD

**Issue by mmarkiew** [idnow/de.idnow.android#18]
Hi,
in the latest version of the SDK the Done button on very last screen (Identification completed screen) is not working.  After clicking on the button, nothing happens. Process can be finished only using the back button. I tested the SDK with the same result on devices mentioned below:

- LG G5    Android 6.0.1
- Sony Xperia Z5    Android 5.1.1
- Samsung S8    Android 7.0

**Comment by andreaskofer** [comment]
Hello,

thank you for your feedback. The issue has been addressed/fixed already and will be available with the next minor release of our SDK.

Best regards,
Andreas

**Comment by hkretzschmar** [comment]
Hi mmarkview,

we just released a new SDK version 3.4.4 which fixes this issue.

Kind regards
Holger
