### ISSUE TITLE
UnsatisfiedLinkError: couldn't find "libopentok.so"  

### ISSUE THREAD

**Issue by javicuesta** [idnow/de.idnow.android#2]
Libopentok library cannot be found in arm64 jniLib folder. 

nativeLibraryDirectories=[/data/app/de.number26.android-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libopentok.so"

**Comment by arminbauer** [comment]
See section "Using IDnow with other native libraries (UnsatisfiedLinkError)" for details how to prevent this.
