### ISSUE TITLE
SDK activity does not return if an Ident-ID is provided which was already used

### ISSUE THREAD

**Issue by suzukieng** [idnow/de.idnow.android#27]
SDK version: 3.9.2

If an Ident-ID is provided to the SDK that was already consumed in a previous identification, the SDK will display an error popup that showing the error "The identification for this Ident-ID has already been completed and cannot be restarted". Once the user confirms with OK, the activity just displays a spinner forever.

`onActivityResult` of the calling Activity is never triggered, the IDnow Activity does not seem to `finish()` itself.

**Comment by andreaskofer** [comment]
Hello Alex,

can you please use our Service Desk tool at https://support.idnow.de as this will allow us to distribute your question within our team and also ask more specific questions about your account allowing us to look into server side logs more easily.

Thank you and best regards,
Andreas
