### ISSUE TITLE
Why do you need Jackson and Gson?

### ISSUE THREAD

**Issue by akohout** [idnow/de.idnow.android#5]
Both deal with JSON (de)serialization, so why are both required?

**Comment by MathiasGrasy** [comment]
At the beginning we used Gson mostly for deserialization the Retrofit responses. For our socket calls we use a library that comes with Jackson, that's why both of them are currently needed. But you're right actually both are for (de)serialization JSON.

**Comment by akohout** [comment]
Okay, so why not just removing Gson if you have to import Jackson?

**Comment by panzerfahrer** [comment]
Please consider removing at least one of the dependencies! Or even better, abstract the json de-/serialization completely and let the lib-consumer decided on which to use.

**Comment by arminbauer** [comment]
In version 2.3.0, the Jackson dependency has been removed.
