### ISSUE TITLE
Consistent use of Git tags

### ISSUE THREAD

**Issue by sonicdoe** [idnow/de.idnow.android#58]
Looking at the last seven releases, some are tagged with just `de.idnow.android-X.Y.Z` and some are tagged with both `de.idnow.android-X.Y.Z` and `de.idnow.android.X.Y.Z` (note the period):

- [`de.idnow.android.4.1.5`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android.4.1.5)
- [`de.idnow.android-4.1.5`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android-4.1.5)
- [`de.idnow.android-4.1.4`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android-4.1.4)
- [`de.idnow.android-4.1.3`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android-4.1.3)
- [`de.idnow.android.4.1.2`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android.4.1.2)
- [`de.idnow.android-4.1.2`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android-4.1.2)
- [`de.idnow.android.4.1.1`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android.4.1.1)
- [`de.idnow.android-4.1.1`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android-4.1.1)
- [`de.idnow.android-4.1.0`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android-4.1.0)
- [`de.idnow.android-4.0.0`](https://github.com/idnow/de.idnow.android/releases/tag/de.idnow.android-4.0.0)

It would be helpful if each release only has a single Git tag and would use the same format.

**Comment by souheib93** [comment]
Correct git tag is de.idnow.android-X.Y.Z, I fixed all git tags.
