### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by tfcporciuncula** [idnow/de.idnow.android#59]
https://developer.android.com/jetpack/androidx/migrate

**Comment by GitHubMurt** [comment]
otherwise I will stuck with 4.1.6 v

**Comment by GitHubMurt** [comment]
Currently the only way to compromise old android styles is to change apply own theme for application 
`
 <application
android:theme="@style/AppTheme"
tools:replace="android:theme"
`

otherwise application throws You need to use a Theme.AppCompat theme (or descendant) with this activity

**Comment by aare-undo-idnow** [comment]
I apologise your issue wasn't addressed, however, we have by now migrated to androidx. Closing this
