### ISSUE TITLE
App getting crash after open Idnow (My app migrated to AndroidX)

### ISSUE THREAD

**Issue by MeenakshiNaiduPinisetti** [idnow/de.idnow.android#63]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
        at de.idnow.sdk.util.IDnowExternalLog.logExternally(IDnowExternalLog.java:21)
        at de.idnow.sdk.IDnowSDK.getApplicationName(IDnowSDK.java:568)
        at de.idnow.sdk.IDnowSDK.initialize(IDnowSDK.java:444)

**Comment by GitHubMurt** [comment]
Yeah IDNow is incompatibilie with MaterialTheme, You app styles have to iherit from Material whereas IdNow from AppCompact

   <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        ...
    </style>

    <style name="IdnowSdkTheme" parent="Theme.AppCompat.Light.NoActionBar">
        ...
    </style>

This will save You from crash, but IDNow styles will be destoryed - U will see old fasion dialog , progress bar like in KitKat

**Comment by aare-undo-idnow** [comment]
I apologise your issue wasn't addressed, however, we've also migrated to androidx and this should no longer be the case. Closing.
